downloading ignite dep shouldn't be in entrypoint

diff --git a/scripts/dev/ignite b/scripts/dev/ignite
--- a/scripts/dev/ignite
+++ b/scripts/dev/ignite
@@ -18,46 +18,37 @@ if [ "$USE_IGNITE_LOADER" = "true" ]; then
     resultsFile=/data/.purpur.env
 
     if [[ $PURPUR_DOWNLOAD_URL ]]; then
-    if ! mc-image-helper install-purpur \
-        --output-directory=/data \
-        --results-file="$resultsFile" \
-        --url="$PURPUR_DOWNLOAD_URL}"; then
-        log "ERROR: failed to download from custom Purpur URL"
-        exit 1
-    fi
-    # grab SERVER and export it
-    set -a
-    # shellcheck disable=SC1090
-    source "${resultsFile}"
-    set +a
+        if ! mc-image-helper install-purpur \
+            --output-directory=/data \
+            --results-file="$resultsFile" \
+            --url="$PURPUR_DOWNLOAD_URL}"; then
+            log "ERROR: failed to download from custom Purpur URL"
+            exit 1
+        fi
+        # grab SERVER and export it
+        set -a
+        # shellcheck disable=SC1090
+        source "${resultsFile}"
+        set +a
 
     else
-    args=(
-        --output-directory=/data
-        --results-file="$resultsFile"
-        --version="$VERSION"
-    )
-    if [[ $PURPUR_BUILD ]]; then
-        args+=(--build="$PURPUR_BUILD")
-    fi
-    if ! mc-image-helper install-purpur "${args[@]}"; then
-        log "ERROR: failed to download Purpur"
-        exit 1
-    fi
-    # grab SERVER and export it
-    set -a
-    # shellcheck disable=SC1090
-    source "${resultsFile}"
-    set +a
-    fi
-
-    if isTrue "$USE_IGNITE_LOADER"; then
-    downloadUrl="https://github.com/vectrix-space/ignite/releases/latest/download/ignite.jar"
-
-    if ! IGNITE_JAR=$(get --output-filename --skip-up-to-date --output /data "$downloadUrl"); then
-        log "ERROR: failed to download Ignite loader jar from $downloadUrl"
-        exit 1
-    fi
+        args=(
+            --output-directory=/data
+            --results-file="$resultsFile"
+            --version="$VERSION"
+        )
+        if [[ $PURPUR_BUILD ]]; then
+            args+=(--build="$PURPUR_BUILD")
+        fi
+        if ! mc-image-helper install-purpur "${args[@]}"; then
+            log "ERROR: failed to download Purpur"
+            exit 1
+        fi
+        # grab SERVER and export it
+        set -a
+        # shellcheck disable=SC1090
+        source "${resultsFile}"
+        set +a
     fi
 
     # Normalize on Spigot for later operations
